import { CalendarHeart, CakeSlice, Check, Clock3, MessageCircle, PartyPopper, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { Celebration } from '../../../domain/customer/customer-experience.types'
import { useCelebrations, useCustomerExperienceActions } from '../../../features/customer/hooks/useCustomerExperience'
import { EmptyState, ErrorState, PrimaryButton, Skeleton } from '../../../shared/components'
import { CustomerPageHeader } from '../components/Stage5Ui'
import { useCelebrationAutomation, useRetentionActions } from '../../../features/retention/hooks/useRetention'
import type { CelebrationStage } from '../../../domain/retention/retention.types'
import { Link } from 'react-router-dom'

const monthName = (month: number) => new Intl.DateTimeFormat('en-IN', { month: 'long' }).format(new Date(2026, month - 1, 1))

export default function CelebrationsPage() {
  const celebrations = useCelebrations(); const automation = useCelebrationAutomation(); const actions = useCustomerExperienceActions(); const retentionActions = useRetentionActions(); const [adding, setAdding] = useState(false)
  const [draft, setDraft] = useState<Omit<Celebration, 'id' | 'customerId'>>({ type: 'BIRTHDAY', label: '', relation: '', day: 1, month: 1 })
  if (celebrations.isError) return <div className="stage5-page"><ErrorState retry={() => void celebrations.refetch()} /></div>
  const create = () => actions.createCelebration.mutate(draft, { onSuccess: () => { setAdding(false); setDraft({ type: 'BIRTHDAY', label: '', relation: '', day: 1, month: 1 }) } })
  return <div className="stage5-page celebrations-page"><CustomerPageHeader eyebrow="PIZZA MOMENTS" title="Celebrations" back="/app/profile" action={<button className="icon-button" aria-label="Add celebration" onClick={() => setAdding(true)}><Plus /></button>} />
    <section className="celebration-hero"><PartyPopper /><div><span>CELEBRATE WITH THE WAVE</span><h2>Good dates deserve good pizza.</h2><p>Save the day and we’ll make future celebration picks more relevant.</p></div></section>
    {automation.data && <section className="birthday-automation"><header><div><span>UPCOMING BIRTHDAY AUTOMATION</span><h2>{automation.data.label}</h2><p>{new Date(automation.data.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long' })} · DemoClock journey</p></div><Clock3 /></header><div className="birthday-timeline">{automation.data.touchpoints.map((touchpoint) => <button key={touchpoint.stage} className={touchpoint.sent ? 'sent' : ''} disabled={touchpoint.sent || retentionActions.celebration.isPending} onClick={() => retentionActions.celebration.mutate(touchpoint.stage as CelebrationStage)}><i>{touchpoint.sent ? <Check /> : <span />}</i><strong>{touchpoint.stage.replace('T_MINUS_', 'T−')}</strong><small>{touchpoint.sent ? 'Simulated' : touchpoint.label}</small></button>)}</div><footer><span>No waiting days: each step runs against a deterministic DemoClock scenario.</span><Link to="/app/support"><MessageCircle /> VIEW SHARED THREAD</Link></footer></section>}
    {celebrations.isPending ? <Skeleton className="celebration-skeleton" /> : celebrations.data?.length ? <div className="celebration-list">{celebrations.data.map((item) => <article key={item.id}><i>{item.type === 'BIRTHDAY' ? <CakeSlice /> : <CalendarHeart />}</i><div><span>{item.type}</span><h2>{item.label}</h2><p>{item.relation} · {item.day} {monthName(item.month)}</p></div><button className="icon-button" aria-label={`Delete ${item.label}`} onClick={() => actions.deleteCelebration.mutate(item.id)}><Trash2 /></button></article>)}</div> : <EmptyState title="No dates saved" message="Add a birthday, anniversary or custom Pizza Wave moment." />}
    {adding && <section className="celebration-form"><h2>Add a celebration</h2><label>TYPE<select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as Celebration['type'] })}><option>BIRTHDAY</option><option>ANNIVERSARY</option><option>CUSTOM</option></select></label><label>LABEL<input placeholder="Mom's birthday" value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} /></label><label>RELATION<input placeholder="Mom" value={draft.relation} onChange={(event) => setDraft({ ...draft, relation: event.target.value })} /></label><div><label>DAY<input type="number" min="1" max="31" value={draft.day} onChange={(event) => setDraft({ ...draft, day: Number(event.target.value) })} /></label><label>MONTH<select value={draft.month} onChange={(event) => setDraft({ ...draft, month: Number(event.target.value) })}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>{monthName(index + 1)}</option>)}</select></label></div><PrimaryButton disabled={!draft.label.trim() || !draft.relation.trim() || actions.createCelebration.isPending} onClick={create}>SAVE DATE</PrimaryButton><button onClick={() => setAdding(false)}>CANCEL</button></section>}
  </div>
}
