import React from 'react'
import ReactDOM from 'react-dom/client'
import '@fontsource/phudu/600.css'
import '@fontsource/phudu/700.css'
import '@fontsource/poppins/400.css'
import '@fontsource/poppins/500.css'
import '@fontsource/poppins/600.css'
import '@fontsource/poppins/700.css'
import './styles/globals.css'
import './styles/stage2.css'
import './styles/stage3.css'
import './styles/stage4.css'
import './styles/stage5.css'
import './styles/stage6.css'
import './styles/stage7.css'
import './styles/stage8.css'
import './styles/stage9.css'
import './styles/stage10.css'
import { AppProviders } from './app/providers/AppProviders'
import { AppRouter } from './app/router/AppRouter'

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppProviders><AppRouter /></AppProviders></React.StrictMode>)
