export type PaymentStatus = 'NOT_STARTED' | 'PENDING' | 'CONFIRMED' | 'FAILED' | 'RECONCILING'
export type AcceptanceStatus = 'NOT_APPLICABLE' | 'AWAITING_ACCEPTANCE' | 'REVIEW_REQUIRED' | 'ACCEPTED' | 'REJECTED'
export type FulfillmentStatus = 'NOT_STARTED' | 'SCHEDULED' | 'PREP_DUE' | 'PREPARING' | 'READY' | 'DISPATCHED' | 'PICKED_UP' | 'DELIVERED' | 'STORE_COMPLETED' | 'CANCELLED'
